version: "3"
services:
  nginx:
    image: romanoffs/rs-nginx:1.15.7
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx